"""Real-machine injected voice-capture regression for the reBot arm config.

Unlike the other e2e tests (which use client_vad_backend="energy"), this suite
replicates the PRODUCTION reBot voice path — client_vad_backend="off" + the
energy gate — so it exercises the 2026-06-13 first-utterance fixes against the
LIVE SLV ASR (orin-nx:8621):
  * P0 energy-gate pre-roll (command onset survives the gate)
  * P1 reconnect_on_wake=false (first post-wake command not dropped)
  * P2 short wake-tone suppression

Scripted WAVs are injected through the real mic pump → real SLV ASR; we assert
on the ASR final text the server returns. macOS `say -v Tingting` fixtures are
generated by conftest / the cmd_*.wav generator. The fade-in variants press the
onset below the gate threshold to prove the pre-roll recovers it.

Run: pytest tests/e2e/test_rebot_voice_capture.py -v -s  (needs orin-nx live)
"""
from __future__ import annotations

import asyncio
import subprocess
import wave
from dataclasses import replace

import aiohttp
import numpy as np
import pytest

from .conftest import run_agent, WAV_DIR
from .fake_audio import ScriptedAudioIO

# reBot command corpus (macOS `say -v Tingting`; committed for non-macOS CI).
_REBOT_CMDS = [
    ("cmd_grab_box", "抓盒子"),
    ("cmd_grab_box_full", "把盒子抓起来"),
    ("cmd_put_back", "放回原位"),
    ("cmd_put_back_full", "把盒子放回原位"),
    ("cmd_wave", "挥手"),
    ("cmd_go_home", "回家"),
    ("cmd_search_box", "找一下盒子"),
]
# Fade-in variants: linearly ramp the first 300ms so the onset sits BELOW the
# energy-gate threshold — the only way to exercise the P0 pre-roll recovery
# (clean `say` output starts loud and never trips the gate-truncation bug).
_FADEIN = [("cmd_grab_box", 300), ("cmd_put_back_full", 300)]


def _ensure_rebot_wavs() -> None:
    WAV_DIR.mkdir(parents=True, exist_ok=True)
    have_say = subprocess.run(["which", "say"], capture_output=True).returncode == 0
    for name, text in _REBOT_CMDS:
        out = WAV_DIR / f"{name}.wav"
        if out.exists() and out.stat().st_size > 0:
            continue
        if not have_say:
            raise RuntimeError(f"{out.name} missing and `say` unavailable; commit fixtures.")
        subprocess.run(
            ["say", "-v", "Tingting", text, "-o", str(out),
             "--data-format=LEI16@16000", "--file-format=WAVE"],
            check=True, capture_output=True,
        )
    for src, fade_ms in _FADEIN:
        out = WAV_DIR / f"{src}_fadein.wav"
        if out.exists() and out.stat().st_size > 0:
            continue
        with wave.open(str(WAV_DIR / f"{src}.wav"), "rb") as w:
            sr = w.getframerate()
            a = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16).astype(np.float32)
        ramp = np.linspace(0.0, 1.0, min(int(sr * fade_ms / 1000), len(a)))
        a[: len(ramp)] *= ramp
        with wave.open(str(out), "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(sr)
            w.writeframes(a.astype(np.int16).tobytes())


_ensure_rebot_wavs()


def _rebot_voice_config(base):
    """Production reBot voice parameters layered onto the e2e base config."""
    return replace(
        base,
        pipeline_mode="wake_word",
        wake_command_single_turn=False,
        client_vad_backend="off",        # server-VAD path → energy gate runs
        energy_gate_enabled=True,
        energy_gate_open_rms=0.020,
        energy_gate_close_rms=0.010,
        energy_gate_hangover_ms=300,
        mic_makeup_gain=3.0,
        gate_drive_eos=True,
        gate_eos_min_speech_ms=250,
        gate_eos_delay_ms=200,
        reconnect_on_wake=False,
        mic_drop_while_speaking=True,
        sleep_timeout_s=45.0,
        system_prompt="你是机械臂语音助手，简洁回应。",
    )


async def _wake(app, cfg) -> None:
    port = cfg.metadata["dashboard_port"]
    async with aiohttp.ClientSession() as s:
        async with s.post(f"http://127.0.0.1:{port}/api/control/wake") as r:
            assert r.status == 200


def _last_user_text(app) -> str:
    for msg in reversed(app.session.history or []):
        if msg.get("role") == "user":
            return str(msg.get("content") or "")
    return ""


@pytest.mark.asyncio
async def test_grab_box_clean_onset(test_config):
    """Baseline: a clean (loud-onset) '抓盒子' is transcribed with the object
    word intact — confirms the gate path + live ASR work end to end."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([(1500, WAV_DIR / "cmd_grab_box.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _last_user_text(app)
        print(f"\n[clean onset] ASR final = {text!r}")
        assert "盒子" in text, f"object word lost: {text!r}"


@pytest.mark.asyncio
async def test_grab_box_low_onset_preroll(test_config):
    """P0: a faded-in '抓盒子' whose onset sits BELOW the gate threshold. The
    pre-roll must replay the buffered onset so the ASR still hears the leading
    '抓', not just '盒子'."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([(1500, WAV_DIR / "cmd_grab_box_fadein.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _last_user_text(app)
        print(f"\n[low onset + preroll] ASR final = {text!r}")
        # The onset survives if the leading verb '抓' is recovered. We assert
        # the object word at minimum and report the verb so a regression
        # (onset truncated to just '盒子') is visible.
        assert "盒子" in text, f"object word lost: {text!r}"
        assert "抓" in text, f"ONSET LOST — preroll did not recover '抓': {text!r}"


@pytest.mark.asyncio
async def test_command_immediately_after_wake(test_config):
    """P1: the FIRST command after wake must land. Inject the command only
    AFTER wake completes (runtime inject, not a fixed pre-wake script delay) so
    we test the real "wake then speak" order, not a capture-vs-wake race. With
    reconnect_on_wake=false the hot WS persists so the utterance isn't dropped
    in a reconnect window."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([])  # nothing pre-wake
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        # Past the wake-tone suppression (250ms) — the user's command proper.
        await asyncio.sleep(0.5)
        audio.inject(WAV_DIR / "cmd_grab_box.wav")
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _last_user_text(app)
        print(f"\n[post-wake command] ASR final = {text!r}")
        assert "盒子" in text, f"first post-wake command lost/truncated: {text!r}"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "wav,must_contain",
    [
        ("cmd_put_back_full", "放回"),
        ("cmd_wave", "挥手"),
        ("cmd_go_home", "回"),
        ("cmd_search_box", "盒子"),
    ],
)
async def test_command_word_asr_accuracy(test_config, wav, must_contain):
    """Probe ASR accuracy of each demo command word — surfaces homophone /
    truncation issues per command (e.g. '挥手'→'灰手', '回家'→'回家了')."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([(1200, WAV_DIR / f"{wav}.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _last_user_text(app)
        print(f"\n[asr {wav}] = {text!r}  (need {must_contain!r})")
        assert must_contain in text, f"{wav}: got {text!r}, missing {must_contain!r}"


@pytest.mark.asyncio
async def test_consecutive_commands_during_reply_are_dropped(test_config):
    """P3 PROBE (known limitation, not yet fixed): mic_drop_while_speaking=true
    means a command spoken WHILE the agent is still replying/acting is dropped.
    This documents the behaviour with a real injection so a future AEC-based
    full-duplex change has a regression baseline to flip.

    Inject a 2nd command 0.5s after the 1st (well within the 1st turn's TTS
    reply) → only the FIRST command should be transcribed."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await asyncio.sleep(0.5)
        audio.inject(WAV_DIR / "cmd_grab_box_full.wav")   # "把盒子抓起来"
        await probe.wait_event("on_user_utterance", timeout=25)
        first = _last_user_text(app)
        # Barge in with a different command while the reply is playing.
        await asyncio.sleep(0.3)
        audio.inject(WAV_DIR / "cmd_wave.wav")            # "挥手"
        await asyncio.sleep(4.0)
        latest = _last_user_text(app)
        print(f"\n[P3 during-reply] first={first!r} latest={latest!r}")
        # The barge-in command did NOT replace the transcript — it was dropped.
        # (When P3 is fixed with AEC this assertion should be revisited.)
        assert "抓" in first, f"first command not captured: {first!r}"
        assert "挥手" not in latest, (
            f"P3 baseline changed — barge-in command '挥手' got through: {latest!r}. "
            "If AEC/full-duplex was intentionally enabled, update this probe."
        )
